# -*- coding: utf-8 -*-
"""ArithmeticOperators.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15n_YAwC33W3ag5Cxi5X_D2PwyuIIa-eo
"""

a = int(input())
b = int(input())
print(a+b)
print(a-b)
print(a*b)