# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ricJLBtBbBPLkml7q5aemWqLVcJjHT4E
"""

a = int(input())
b = int(input())
print(a//b)
print(a/b)
