# -*- coding: utf-8 -*-
"""HelloWorld.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/akiwelekar/c0d59f728a1f6e8eacfc2a290b0c54bd/helloworld-py.ipynb
"""

print("Hello World!, Arvind")
